In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

In [2]:
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 2D array
arr_2d = arr_1d.reshape((2, 3))
print("2D Array:\n", arr_2d)

# Reshape to a 3x2 2D array
arr_another_2d = np.reshape(arr_1d, (3, 2))
print("Another 2D Array:\n", arr_another_2d)

# Reshape using -1 for automatic dimension inference
arr_inferred_shape = arr_1d.reshape((-1, 1))
print("Array with inferred shape:\n", arr_inferred_shape)

2D Array:
 [[1 2 3]
 [4 5 6]]
Another 2D Array:
 [[1 2]
 [3 4]
 [5 6]]
Array with inferred shape:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [3]:
# Function for create polyomial of given drgree
def make_polynomial(X, degree):
    return np.power(X, np.arange(0, degree))


# Sample data with two features
X = np.array([[1, 2], [3, 4]])
# X2 = np.array([1, 2, 3, 4])

# Create polynomial features of degree 2
poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X)
X_poly2 = poly.transform(X)

print(X_poly, X_poly2, sep="\n==\n")
print(make_polynomial(X, degree=2))

[[ 1.  2.  1.  2.  4.]
 [ 3.  4.  9. 12. 16.]]
==
[[ 1.  2.  1.  2.  4.]
 [ 3.  4.  9. 12. 16.]]
[[1 2]
 [1 4]]


In [4]:
print(np.power(X, 6))
var = np.arange(0, 5)
print(var)
print(np.power(var, 2))
print(np.power(var, var))

[[   1   64]
 [ 729 4096]]
[0 1 2 3 4]
[ 0  1  4  9 16]
[  1   1   4  27 256]


In [5]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures


# Your corrected function
def make_polynomial(X, degree):
    return np.power(X.reshape(-1, 1), np.arange(0, degree))


X = np.random.randint(10, size=6)
# Reshape X to a 2D array as required by sklearn
X_2d = X.reshape(-1, 1)

print("Original X values:")
print(X, "\n", X_2d)

Original X values:
[5 9 0 8 0 3] 
 [[5]
 [9]
 [0]
 [8]
 [0]
 [3]]


In [6]:
print("\n--- Your Manual Function Output ---")
print("Polynomial features (degree=2):")
print(make_polynomial(X_2d, degree=3))


--- Your Manual Function Output ---
Polynomial features (degree=2):
[[ 1  5 25]
 [ 1  9 81]
 [ 1  0  0]
 [ 1  8 64]
 [ 1  0  0]
 [ 1  3  9]]


In [7]:
# Correct way to use PolynomialFeatures
xp = PolynomialFeatures(degree=2, include_bias=True)
X_poly_sklearn = xp.fit_transform(X_2d)

print("\n--- Scikit-learn Output ---")
print("Polynomial features (degree=2):")
print(X_poly_sklearn)


--- Scikit-learn Output ---
Polynomial features (degree=2):
[[ 1.  5. 25.]
 [ 1.  9. 81.]
 [ 1.  0.  0.]
 [ 1.  8. 64.]
 [ 1.  0.  0.]
 [ 1.  3.  9.]]


In [8]:
import numpy as np

# Sample data
X = np.array([3, 1, 4, 2])
y = np.array([9, 1, 16, 4])  # y is a function of X (y=X^2)

print("Original X:", X)
print("Original y:", y)

# Get the indices that would sort X
sorted_indices = np.argsort(X)

# Use these indices to sort both X and y
X_sorted = X[sorted_indices]
y_sorted = y[sorted_indices]

print("\nSorted X:", X_sorted)
print("Sorted y:", y_sorted)

# Output:
# Original X: [3 1 4 2]
# Original y: [ 9  1 16  4]
#
# Sorted X: [1 2 3 4]
# Sorted y: [ 1  4  9 16]

Original X: [3 1 4 2]
Original y: [ 9  1 16  4]

Sorted X: [1 2 3 4]
Sorted y: [ 1  4  9 16]
